version: '3'

services:
  provider:
   image: dtr.rogfk.no/fint-beta/provider:PR-9
   ports:
     - "8410:8080"
   environment:
    TZ: Europe/Oslo
    server.context-path: /administrasjon/organisasjon/provider
    fint.events.orgIds: "pwf.no, fint.health"
    fint.events.component: pwf
    fint.events.env: pwf
    fint.audit.mongo.connection-string: "mongodb://fint-mongo:iehyvB6S5E5XvH9yYFK4K8MBlH4WVI2i9Mbsil2hoKMWEUIOwwGZATB41e1kJ8AN3LueuQf2lDoiTo0GSrkS4w==@fint-mongo.documents.azure.com:10255/%s?ssl=true&replicaSet=globaldb"
    fint.audit.mongo.databasename: fint-audit-pwf
    fint.hazelcast.members: consumer,provider
   deploy:
    placement:
     constraints:
      - node.role == worker
    replicas: 1
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s

  consumer:
   image: dtr.rogfk.no/fint-beta/consumer-organisasjon:1.4.0-2.6.0-rc-1
   ports:
     - "8411:8080"
   environment:
    TZ: Europe/Oslo
    server.context-path: /administrasjon/organisasjon
    fint.consumer.override-org-id: "true"
    fint.consumer.default-org-id: "pwf.no"
    fint.events.orgIds: "pwf.no, fint.health"
    fint.events.component: pwf
    fint.events.env: pwf
    fint.relations.default-base-url: "https://play-with-fint.felleskomponent.no"
    fint.audit.mongo.databasename: fint-audit-pwf
    fint.consumer.cache-manager: hazelcast
    fint.hazelcast.members: consumer,provider
   deploy:
    placement:
     constraints:
      - node.role == worker
    replicas: 1
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s

  health-adapter:
     image: dtr.rogfk.no/fint-beta/health-adapter:1.1.0
     #ports:
     #  - "8402:8080"
     environment:
      TZ: Europe/Oslo
      springfox.title: "Play-With-FINT Health Adapter"
      fint.adapter.organizations: fint.health
      fint.adapter.sse-endpoint: https://play-with-fint:8080/administrasjon/organisasjon/provider/sse/%s
      fint.adapter.status-endpoint: https://play-with-fint:8080/administrasjon/organisasjon/provider/status
      fint.adapter.response-endpoint: https://play-with-fint:8080/administrasjon/organisasjon/provider/response
     deploy:
      placement:
       constraints:
        - node.role == worker
      replicas: 1
      restart_policy:
       condition: on-failure
       delay: 5s
       max_attempts: 3
       window: 120s
