version: '3'

services:
  provider:
   image: dtr.rogfk.no/fint-beta/provider
   ports:
     - "8410:8080"
   environment:
    TZ: Europe/Oslo
    server.context-path: /administrasjon/organisasjon/provider
    fint.events.orgIds: "pwf.no, fint.health"
    fint.events.component: pwf
    fint.events.env: pwf
    fint.audit.mongo.hostname: 152.93.213.138
    fint.audit.mongo.databasename: fint-audit-pwf
    fint.hazelcast.members: consumer,provider
   deploy:
    placement:
     constraints:
      - node.role == worker
    replicas: 1
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s

  consumer:
   image: dtr.rogfk.no/fint-beta/consumer-organisasjon
   ports:
     - "8411:8080"
   environment:
    TZ: Europe/Oslo
    server.context-path: /administrasjon/organisasjon
    fint.events.orgIds: "pwf.no, fint.health"
    fint.events.component: pwf
    fint.events.env: pwf
    fint.relations.default-base-url: "https://play-with-fint.felleskomponent.no"
    fint.audit.mongo.hostname: 152.93.213.138
    fint.audit.mongo.databasename: fint-audit-pwf
    fint.consumer.cache-manager: hazelcast
    fint.hazelcast.members: consumer,provider
   deploy:
    placement:
     constraints:
      - node.role == worker
    replicas: 1
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s

  health-adapter:
     image: dtr.rogfk.no/fint-beta/health-adapter
     #ports:
     #  - "8402:8080"
     environment:
      TZ: Europe/Oslo
      springfox.title: "Play-With-FINT Health Adapter"
      fint.adapter.organizations: fint.health
      fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/organisasjon/provider/sse/%s
      fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/organisasjon/provider/status
      fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/organisasjon/provider/response
     deploy:
      placement:
       constraints:
        - node.role == worker
      replicas: 1
      restart_policy:
       condition: on-failure
       delay: 5s
       max_attempts: 3
       window: 120s

