springfox:
 title: 'FINT Consumer Organisasjon'
 version: '@version@'

local:
 server:
  port: 8080

event-model-version: '@eventModelVersion@'
administrasjon-model-version: '@administrasjonModelVersion@'
relation-model-version: '@relationModelVersion@'