fint:
 events:
  orgs: mock.no

 audit:
  test-mode: true

 relations:
  force-https: false

 consumer:
  cache:
   initialDelay:
    organisasjonselement: 1000

link-mapper-base-url: http://localhost:8080